[tool.ruff]
# Set line length
line-length = 120

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "build",
    "dist",
    "*.egg-info",
]

# Python version
target-version = "py38"

[tool.ruff.lint]
# Enable flake8 rules
select = ["E", "F", "W", "B", "I", "N", "UP", "S", "A", "C", "DTZ", "EM", "ISC", "PIE", "PT", "Q", "RET", "SIM", "TID", "ARG", "PLE", "PLR", "PLW"]

# Ignore specific rules
ignore = [
    "E501",  # Line too long - let black handle this
    "S101",  # Use of assert in tests
    "PLR0913",  # Too many arguments
    "C901",  # Too complex
    "PLR0912",  # Too many branches
    "EM101",  # Exception string literal
    "S311",  # Random not for crypto (OK for game characters)
    "PLR2004",  # Magic value comparisons
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "PLR2004", "PT011", "ARG002"]  # Allow asserts, magic values, broad pytest.raises, and unused args in tests

[tool.ruff.lint.isort]
known-first-party = ["appearance"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
strict_equality = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/'''